### ISSUE TITLE
img is a void element tag and must not have children

### ISSUE THREAD

**Issue by payner35** [Youpinadi/react-image-responsive#2]
i think this is a warning introduced by react 0.14.x - it complains when you pass anything at all as children in the React.createElement call.  Im not sure though?

![image](https://cloud.githubusercontent.com/assets/939749/12551884/4403cc00-c387-11e5-8422-25c7e9c26351.png)

```
return (
          <div>
            <ImageResponsive type="image" src={image.cdnUrl + '-/resize/600x/'}>
              <Source src={image.cdnUrl + '-/resize/600x/'} maxWidth={500}/>
              <Source src={image.cdnUrl + '-/resize/900x/'} maxWidth={800}/>
              <Source src={image.cdnUrl + '-/resize/1200x/'} maxWidth={1000}/>
            </ImageResponsive>
          </div>
      );
```

using image-background seems to work fine.

**Comment by Youpinadi** [comment]
Should be fixed with v2 (no more `<Source>` children)
